sudo: required

language: go

go_import_path: github.com/bosh-prometheus/bosh_tsdb_exporter

services:
  - docker

jobs:
  include:
    - stage: Run tests
      script: make test

    - stage: Build docker image
      env:
        - DOCKER_IMAGE_NAME=boshprometheus/bosh-tsdb-exporter
        - secure: K4HKdFovpYYpWada/SY3qaFbUp6uI2npJeHs/3m2dhXOBg/qgsGVhSlXHQ4viQ+IfXhXgCqtv2C5KKD652HmNY9X3HJSfbg0it6JisfB8yb5XJK35pRy2SmJ/74QjzqBME13GNKS8bvZ+2hmwL0p6vHwc1gx6Pbbh0FjjyzHy4UBCvd2sxhclxBZq99eCQ+Xgtt9dKPsIFYszA5QN7bE+jZGRuuS7yKcl2+a9lOsCMUn3Dy5enQ510w8/vk4Wq12hkt7sr2CraphK9FEAwnjPhoYljtLb6FBjMo2RHf5LW2vxvCd6mhMojA6p0p8W2eOhdNJa+3Tz1AHjDT8+7zXH25RPkRDJ0LOsLbt/W1dc7vjXz3llQb8JMH2WoL4JrIR/cWCinCfWvAJWRjE/cGHQKPJ67MULUjuGpl9o00dhe1zLXwKracPb9/pej/GkxhWCe+iQT7NEHeDzNxnz9zBtBUJLaFGo1Ixnd7D0AmFbivW9qHO5j9XnufxYhJA0jPM1AwYbhpiRHNOoqcLVlalMLxWxWwXUHcaX4wsfHihbepx5qU3H1U+rzi0IHdknZMNKp57Mp8qO1sAHW8xsVhYv5ib3br6zreczu94fBTA3sviVKN3JMcdFoL7FuGom9kAHpj0jQBLXmG/6y3f/tHjtXmiwl4W2rhXI7BxmYv0mus=
        - secure: lb06KMSfgqnMbNyvNpH/wCFweBUb5is90Ogj19kA5juL5lhF55fR5hFFTMdMSNqaNzeuIOKjabK/QAaWpWT3IP/klfdusrF+Bc7OPPi5+xOPmtPkplzpf9v9mxcR+fvP4l8ReQbXg3Ss8rbx9057Ds7VGg35VgEr6vXk4Fat/QbYXIjDRodUDm0tQ7/D6onmkDITU63+/5zsd2bJqTPEM0L7KfYodT8DYtpHtNBuTyJq1GNPFQcEqm/dmJQ1ShIQcnSg1BDB1T+EtATH50w7FEtbAVDIpo5t7ldwcUCVmBrqZ1hcXUaW1S2JEWFGJ/c/P8QB466tHdgmTQOLewSDvbOAvyxvoTvNvG1UhHpdPHIkMVSO3OQvr7uVCw8PCnMtIr00Ye6jSV/L5UO+CZYW/WOiwE3AFGNRP/Szi1Xqv8OByxb/97DLLbGXkTAmzPjqpcVuNIHbuRXQL3x7u36OSc+7wdq+Iaw60DYNG4bjI6v3euozpr7dd8xlIWbPBV6yrNtaEm+Fbb82U2alQ80/2Ru66Xh61t4WxghWAK1ANYhwwiNQ95HhBsE9v2M/ivda1AC8twJdHRIAhm6pOYjkzOc8yKdltZNVDaLf/S0qyhM/7DuWNT9uf0evCjZdNXokXrwkIteu860rD6iGfEfACnGu0+4oSz2RMPEDcckKW7s=
      script:
        - make crossbuild
        - ln -s .build/linux-amd64/bosh_tsdb_exporter bosh_tsdb_exporter
        - |
          if [ -n "$TRAVIS_TAG" ]; then
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$TRAVIS_TAG
          else
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
          fi
        - |
          if [[ "$TRAVIS_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            docker tag "$DOCKER_IMAGE_NAME:$TRAVIS_TAG" "$DOCKER_IMAGE_NAME:latest"
          fi
        - docker images
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push $DOCKER_IMAGE_NAME
          fi
