sudo: required

language: go

go_import_path: github.com/bosh-prometheus/bosh_tsdb_exporter

services:
  - docker

env:
  matrix:
    - DOCKER_IMAGE_NAME=boshprometheus/bosh-tsdb-exporter
  global:
    - secure: bhaBBkuAKG42EqJJFbACG+PuYg51iaYKlANZVD6rKglXVdBmWghW+h4Qsf70mFwebakh/OLo+uVIVv4dYRuYiUm3ocWtZ4gI8DdO+jtEXbhlaYB8WEK4+iQ08m3sQszhQ75WG65arnmwKq+ZG6LrxqebVEK9ImXgVuwr9NS6vFP+WDCbywcg5q9vnLI+1V41SVYzlYQTp/36jMr64/etF9hYlennFYPq11U6U6aB5AyIbJmTL8VoDTLsN45bRy4QPO13JnxG/P0Nv66cbn4X/jUw9NhEC4FwniKohpDBHTzTOz1zVBIe4Hat3jJ29e+jImCXewQWacuQV/kMTxrTMWwRZVBCOrvQGolDr7geh2ZHrvLILH5uiAZ7dQ15uskv3YT7ZyywiDuddbuDSeoIDIpEEXJ7RPe9LRq1qrZ6rkKVQ0EpHZr4vpRRJb7d/N9sDcwjXJkkaY68/BY8Lfyot0HlzdPIdYOF54wwfEHHb0uv2Uq4w7i2iA1qrAq0SVR+NKT0usRaklGzWOJy9c+AS8pZwdycDoLeLMpboXUC+bUQvimP85hy22pcl/WDtkDemTFZqPedSiYtmN7kheJLCErINkVgMXXYYPwjTRWQSGVZLqN9CCAPHi1kUV19qpF8lvDH3PolD53UhzClT+r7jPqmwoUEma+LKCHf5zudcas=
    - secure: MaLxEaj/exDCD+3vycDJUWUlFLuTpUxZ+axqULAqNI0fHv2YhrRoJfFFEDQoxD/uWt2hrKB2YvxLY1dQJOoTMZPQCdrRi/U2xVzSE8TwxpNQ2YmDJCWDxvET+ZlK9U6p8MFhiEReE2/C/+reB6x8EOBzCasayR/QWuwbuGBo7+N+Phr3bwbZaQm/6wHG83OGROB52FLLi0NNJ6CTPuyOj6tdNIAs7HVGhW1LtYPqJ3TGvSGtsWxvoHKF+7xnfw/MDHKmMDca1pyza7sGHAo0bswXHS4b0HESrt91uCWnu6m81ulY/+l9n3scRtXd70jvLq04HgyaA6OGppsXr0BdIaHbPDQey4gphyCSiCykKoTQKCba3+3ICvlECxLKyXdnMWcbQwuc71tyNVZot6JO2TEXcATuRXhiP0tkaIhacCPt1k1ZxZKtdGYcSdiXoRmapdo5m//iLa3ZQ5CAdggpV8/sJ8DNxuQRBzu+hiPYnpZ5vWR2NImA3olVKgnwEnUJD1M2WdSbqfswBcSOiQXmSMssN/zAJiaWnRipXPNYwdbY5jEhJ3bZOvrW0DBaUpsPWeoObkAvjWVe4ArivPdTHFV7E1IuZkv566AAuS2rj25Xr1pghl8QwWCsX1envDnw9qbnHlsx9gMfmszZ+KmGLJz0CthkcarnJGfjSHdIET8=
    - secure: q/gQWbgQieuxLRM07AZtXg9CLu9qToehxwEPmhYETKNAqg4wdxfHNKodzJtyMlTVeRhcKVThdhLGVaFPAovuvNer09HLytnnW3NMrU1DWekYr/5pEiE2jNMCR4X4/sm79VH4B1swredB9EGqUMYKuqFBxIx5XTGLjlGiSR3jMRLIHTvM2bUV2aTCRnAxoX7VZ2oNfyzjCqI/ESFSy1oCg2H5qWkglpSZ1XrAYaCuC0DZbyN4IfD7WvRHqWgeCkcON4UkuHaRurpntRju0db6PsSSc5uljhGLpUyMMZr5k8DFEFv2gkxl/U5TMSyVC3wTHHBXcC9osZs8b/poHxNIybGq1D9ESHPqenQVWx9aSpLxEzRRdfdYHfXddFqZZbJvsOffrQINsRJmOss0GiBrW6hgehxXII3DRh8PhKQBb7vI1THIQ+B+Gf8+UpN1R27IgtUOU8DcyJ746KRteOt7m8YEKL4oMenBPaIpHN+AlMuWEkuhQhudYAbmoYrw+UhLfO9rcWz4f5B1Dqy2K9eZ3kfOQfioJ5hrxLwfen9mxzJM6a3dMQtYlwwXdE+CJ7RHpxIaltXdQC65YnYN784OxOguWaTPu9QGC3BnBfi608+lNe7llL4MtgYFVUoCYtX1b2bVecDH5/5GLCaAbbLoj/NAiF8hgQZekBsq0WoBtjI=

jobs:
  include:
    - stage: tests
      script: make test
    - stage: docker image
      script:
        - make crossbuild
        - ln -s .build/linux-amd64/bosh_tsdb_exporter bosh_tsdb_exporter
        - |
          if [ -n "$TRAVIS_TAG" ]; then
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$TRAVIS_TAG
          else
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
          fi
        - |
          if [[ "$TRAVIS_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            docker tag "$DOCKER_IMAGE_NAME:$TRAVIS_TAG" "$DOCKER_IMAGE_NAME:latest"
          fi
        - docker images
        - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
        - docker push $DOCKER_IMAGE_NAME
