sudo: required

language: go

go_import_path: github.com/bosh-prometheus/bosh_tsdb_exporter

services:
  - docker

env:
  matrix:
    - DOCKER_IMAGE_NAME=boshprometheus/bosh-tsdb-exporter
  global:
    - secure: ieSsCmWrUMxvEpJ/xk1lKJtTVaBqAzs7grM254zSWp0s8pVaejnXAqiYjcPHMpxD0t8u82bp5e34/ExZuhqjhVRtzwSKYkt9aEjiCOzV683dfobpOnIIHVz7YLJO8SGhktQMFVCo/0D1k0hQcniGIZ9D6JvS1Owcx0CzheC4m1pbyXQAaBheFxaA5sltAAnKMHuHjIy58pKdV2zxnfuFnTHBX5m+jOJBCDvhrHxBTwQ1zJGnZ8gxpyWra+t+itwiXKJAUSfczBLbxT8KrIc9cXjDPB6xV3vu41FB/FwF2kekacGA470UkhSMjU7W+WILD1M6UQjhx5omxvnr5v6Zp6x0wqOsMsMV6ObC5Ldmjvy7MUWsoKpOeIGZ10W6/ius1ubWBasnqarU0wyO7x2UHzccGIyshhwjGDXBT26wNmLPjgPk4NzJzaaHNHcCP64JlolpvtVjxa2Xhnhh7++FgihOCBDUVK3MlgCL1H7A/apbIquaDsmqKGnNjz9b6c2DlyTN9qdDqXrMbauXqSymxGm0ckyUh8qsROSYO7HnDjAz4aixp/X20T7NdZa7Mau+EyAROkMlZnCOPg812JXeYp7cUv4ApnFW5/T4TCZQFtkEun4FocG32Ts2KEzpr3tWt5XSVJZ7qhkbqpmZ3JXieN6yjMWmhm/dESdXt9GUvmI=
    - secure: PZpJ0uj74lU3iVoYolYR1El3VOnx8f7iyzZ6loRWzG7YGcpnlb3RyZd4rA2Lia+92HMfxNNcSt5dK/appacnxfHXcHWFlcnq/oidwTHzDW+W7xYoHBXzNE53yRNECSTVR1dvnO/19vT5qoprfOR0p3IVzx7iObtq/EGim0R5nSc8ZAUcAtHtbfRKzCUXKvZNxxate/INxTZuEZaqAC2ty4EMWLJtvcN/k1+x26j3IpWxkwNrNo1hw+AewTv3EKwtQqgFujjJqP6bsywke8FbB6byMCOEQp4TSvmdotJXWETclPtsxx1pODkNxI3D0dxQVyRl9zUfhkJyX0HmtpaHIFGXHVvfnmoE7A9wqbGzI2CUfJKQ3m8kFXmGjfKXbprJaX97/3wwMkCrCzuNSokuU6xkckqqpQCowBFY/muqC0KvVpMAT4TiOWO4E0IMSUu2HUgpaHSq6rqYahG+X6qXRDnDWtAV0KOS6J7sSFEx7IQsVITrP5pu59FTHQI6MrD45s9PAwx2baZuHk3/MS6Gmo+uqY20jTw432LwBgbAmyvH5LkbRvPZBbExW8CxXSkNl8x/8h6jS9dnY91DUxZqr23P/9tXVfPbE1yuXhldWxcjOx+8/sIy2TNxVJGf072DJoTzStWxhTPjM8T1/T8q2bI1ImJ/zCkqrQJVbs8TKRk=

jobs:
  include:
    - stage: tests
      script: make test
    - stage: docker image
      script:
        - make crossbuild
        - ln -s .build/linux-amd64/bosh_tsdb_exporter bosh_tsdb_exporter
        - |
          if [ -n "$TRAVIS_TAG" ]; then
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$TRAVIS_TAG
          else
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
          fi
        - |
          if [[ "$TRAVIS_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            docker tag "$DOCKER_IMAGE_NAME:$TRAVIS_TAG" "$DOCKER_IMAGE_NAME:latest"
          fi
        - docker images
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push $DOCKER_IMAGE_NAME
          fi
